# Generated by Django 3.2 on 2021-04-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
